import { afterEach, describe, expect, it, beforeEach, vi } from 'vitest';
import { compareGscForMonitoring, evaluateCrawlAlert, evaluateGscAlert, evaluatePageSpeedAlert, evaluateSemanticAlert, guardPageSpeedComparison } from '@/services/monitoringAlerts/evaluators';
import { defaultMonitoringAlertSettings, normalizeMonitoringSettings } from '@/services/monitoringAlerts/policy';
import { deliverMonitoringAlert, readMonitoringHistory, reserveMonitoringAlert, saveMonitoringSettings, type MonitoringAlert } from '@/services/monitoringAlerts';
import type { GscPerformanceSnapshot } from '@/services/gscPerformanceTracker';
import type { PageSpeedSnapshot } from '@/services/pagespeedHistory';
import type { CrawlDiffReport } from '@/services/crawlDiff';
import type { SemanticRunComparisonReport } from '@/services/semanticRunComparison';

const send = vi.hoisted(() => vi.fn());
vi.mock('@/services/desktopNotifications/delivery', () => ({ sendProjectNotification: send }));

const gsc = (overrides: Partial<GscPerformanceSnapshot> = {}): GscPerformanceSnapshot => ({ id: 'p|2026-01', captured_at: '2026-01-31T00:00:00Z', site_url: 'sc-domain:example.test', start_date: '2026-01-01', end_date: '2026-01-07', filters: {}, total_clicks: 10, total_impressions: 100, avg_ctr: .1, avg_position: 5, queries: [{ query: 'alpha', clicks: 10, impressions: 100, ctr: .1, position: 5 }], pages: [], queries_may_be_truncated: false, pages_may_be_truncated: false, max_rows_per_dimension: 250, stored_query_rows: 1, stored_page_rows: 0, ...overrides });
const psi = (overrides: Partial<PageSpeedSnapshot> = {}): PageSpeedSnapshot => ({ id: 'psi-2', capturedAt: '2026-01-08T00:00:00Z', url: 'https://example.test/', strategy: 'mobile', formFactor: 'PHONE', scope: 'url', pageSpeed: { source: 'fixture', requestedUrl: 'https://example.test/', finalUrl: 'https://example.test/', strategy: 'mobile', fetchedAt: '2026-01-08T00:00:00Z', lighthouseVersion: null, categories: { performance: .5, accessibility: .9, bestPractices: .9, seo: .9 }, metrics: {}, opportunities: [], fieldExperience: null, originExperience: null }, crux: null, ...overrides });
const semantic = (overrides: Partial<SemanticRunComparisonReport> = {}): SemanticRunComparisonReport => ({ baselineRunId: 'old', currentRunId: 'new', changes: [{ id: 'x', code: 'url-added', direction: 'added', title: 'x', detail: 'x', urls: [], evidence: [] }], counts: { 'url-added': 1, 'url-not-observed': 0, 'content-terms-changed': 0, 'content-link-added': 0, 'content-link-not-observed': 0, 'topic-edge-added': 0, 'topic-edge-not-observed': 0, 'topic-url-coverage-changed': 0, 'query-term-observation-changed': 0 }, truncated: false, guard: { status: 'comparable', reasons: [], provenance: { source: 'stored-crawl-runs', scopeMatched: true, baseline: { runId: 'old', completedAt: '2026-01-01', startUrl: 'https://example.test/', scopeFingerprint: 'scope', pageCount: 1, completeness: 'complete', partial: false, partialReasons: [], provenance: 'stored-crawl-run' }, current: { runId: 'new', completedAt: '2026-01-08', startUrl: 'https://example.test/', scopeFingerprint: 'scope', pageCount: 1, completeness: 'complete', partial: false, partialReasons: [], provenance: 'stored-crawl-run' } } }, ...overrides });
const crawl = (overrides: Partial<CrawlDiffReport> = {}): CrawlDiffReport => ({ status: 'comparable', reasons: [], added: [], removed: [], changed: [{ kind: 'changed', url: 'https://example.test/a', fields: ['title'] }], provenance: { source: 'stored-crawl-runs', scopeMatched: true, baseline: { runId: 'old', completedAt: '2026-01-01', startUrl: 'https://example.test/', scopeFingerprint: 's', pageCount: 1, completeness: 'complete', partial: false, partialReasons: [], provenance: 'stored-crawl-run' }, current: { runId: 'new', completedAt: '2026-01-08', startUrl: 'https://example.test/', scopeFingerprint: 's', pageCount: 1, completeness: 'complete', partial: false, partialReasons: [], provenance: 'stored-crawl-run' } }, ...overrides });

describe('monitoring alert policy', () => {
  beforeEach(() => { localStorage.clear(); send.mockReset().mockResolvedValue(true); });
  afterEach(() => { vi.useRealTimers(); });
  it('requires explicit opt-in and normalizes unsafe settings to bounded values', () => { const value = normalizeMonitoringSettings({ frequency: 'bad', thresholds: { gsc: { declinePercent: -2 } } }); expect(defaultMonitoringAlertSettings().enabled).toBe(false); expect(value.enabled).toBe(false); expect(value.frequency).toBe('daily'); expect(value.thresholds.gsc.declinePercent).toBe(1); expect(value.thresholds.pagespeed.maxWindowDays).toBe(35); });
  it('alerts only on a complete GSC decline', () => { const baseline = gsc(); const current = gsc({ id: 'p|2026-02', start_date: '2026-02-01', end_date: '2026-02-07', queries: [{ query: 'alpha', clicks: 5, impressions: 80, ctr: .06, position: 7 }] }); expect(compareGscForMonitoring(baseline, current)?.type).toBe('gsc'); expect(evaluateGscAlert(baseline, current, undefined, { ...defaultMonitoringAlertSettings(), thresholds: { ...defaultMonitoringAlertSettings().thresholds, gsc: { declinePercent: 20, minImpressions: 101 } } })).toBeNull(); expect(evaluateGscAlert(baseline, current, undefined, { ...defaultMonitoringAlertSettings(), thresholds: { ...defaultMonitoringAlertSettings().thresholds, gsc: { declinePercent: 20, minImpressions: 10 } } })).not.toBeNull(); });
  it('rejects truncated GSC comparison evidence', () => { const baseline = gsc(); const current = gsc({ id: 'p|2026-02', start_date: '2026-02-01', end_date: '2026-02-07', queries_may_be_truncated: true }); expect(evaluateGscAlert(baseline, current)).toBeNull(); });
  it('guards PageSpeed windows and scope before comparing', () => { const baseline = psi({ id: 'psi-1', capturedAt: '2026-01-01T00:00:00Z' }); const current = psi({ id: 'psi-2', capturedAt: '2026-02-20T00:00:00Z' }); expect(guardPageSpeedComparison(baseline, current, 35).reasons).toContain('window-too-wide'); expect(evaluatePageSpeedAlert(baseline, current)).toBeNull(); });
  it('alerts on a PageSpeed category regression while ignoring missing metrics', () => { const baseline = psi({ id: 'psi-1', capturedAt: '2026-01-01T00:00:00Z' }); const current = psi({ pageSpeed: { ...psi().pageSpeed!, categories: { ...psi().pageSpeed!.categories, performance: .3 } } }); expect(evaluatePageSpeedAlert(baseline, current)?.evidence.categories).toBe(1); });
  it('alerts on CrUX regression with a compatible field snapshot', () => { const baseline = psi({ id: 'psi-1', capturedAt: '2026-01-01T00:00:00Z', pageSpeed: null, crux: { source: 'fixture', fetchedAt: '2026-01-01', target: 'https://example.test/', scope: 'url', formFactor: 'PHONE', response: { record: { metrics: { largest_contentful_paint: { percentiles: { p75: 100 } } } } } } }); const current = psi({ pageSpeed: null, crux: { ...baseline.crux!, fetchedAt: '2026-01-08', response: { record: { metrics: { largest_contentful_paint: { percentiles: { p75: 500 } } } } } } }); expect(evaluatePageSpeedAlert(baseline, current)?.evidence.crux).toBe(1); });
  it('does not treat blocked crawl comparisons as changes', () => { expect(evaluateCrawlAlert(crawl({ status: 'blocked' }))).toBeNull(); expect(evaluateCrawlAlert(crawl({ status: 'partial' }))?.partial).toBe(true); });
  it('does not turn truncated semantic data into an alert', () => { expect(evaluateSemanticAlert(semantic({ truncated: true }))).toBeNull(); expect(evaluateSemanticAlert(semantic())).not.toBeNull(); });
  it('does not alert on semantic evidence without a comparable run guard', () => {
    expect(evaluateSemanticAlert(semantic({ guard: undefined }))).toBeNull();
    expect(evaluateSemanticAlert(semantic({ guard: { ...semantic().guard!, status: 'blocked', reasons: ['different-scope'] } }))).toBeNull();
  });
  it('persists one delivery per fingerprint and frequency window', async () => { const alert = { type: 'crawl', sourceId: 'new', title: 'x', body: 'y', occurredAt: '2026-01-08T00:00:00Z', partial: false, evidence: {}, fingerprint: 'f' } as MonitoringAlert; saveMonitoringSettings('p1', { enabled: true, frequency: 'run' }); expect((await deliverMonitoringAlert('p1', alert)).delivered).toBe(true); expect((await deliverMonitoringAlert('p1', alert)).duplicate).toBe(true); expect(readMonitoringHistory('p1')).toHaveLength(1); });
  it('scopes pending reservations per project and caps parallel alerts by type', () => { const settings = { ...defaultMonitoringAlertSettings(), enabled: true }; const first = { type: 'crawl', fingerprint: 'one' } as MonitoringAlert; const second = { ...first, fingerprint: 'two' }; const firstReservation = reserveMonitoringAlert('p1', first, settings); expect(firstReservation?.duplicate).toBe(false); expect(reserveMonitoringAlert('p1', second, settings)?.duplicate).toBe(true); expect(reserveMonitoringAlert('p2', first, settings)?.duplicate).toBe(false); firstReservation?.finish(false); });
  it.each(['daily', 'weekly'] as const)('applies the same-type cap to parallel %s reservations', (frequency) => { const settings = { ...defaultMonitoringAlertSettings(), enabled: true, frequency }; const first = { type: 'semantic', fingerprint: `${frequency}-one` } as MonitoringAlert; const second = { ...first, fingerprint: `${frequency}-two` }; const reservation = reserveMonitoringAlert('p1', first, settings); expect(reservation?.duplicate).toBe(false); expect(reserveMonitoringAlert('p1', second, settings)?.duplicate).toBe(true); reservation?.finish(false); });
  it('separates transport delivery from failed history persistence and blocks same-session retries', async () => { const alert = { type: 'gsc', sourceId: 'new', title: 'x', body: 'y', occurredAt: '2026-01-08T00:00:00Z', partial: false, evidence: {}, fingerprint: 'storage-failure' } as MonitoringAlert; saveMonitoringSettings('p1', { enabled: true, frequency: 'run' }); saveMonitoringSettings('p2', { enabled: true, frequency: 'run' }); const write = vi.spyOn(Storage.prototype, 'setItem').mockImplementation(() => { throw new Error('quota'); }); const result = await deliverMonitoringAlert('p1', alert); const retry = await deliverMonitoringAlert('p1', alert); const otherProject = await deliverMonitoringAlert('p2', alert); write.mockRestore(); expect(result).toMatchObject({ delivered: true, persisted: false }); expect(retry).toMatchObject({ delivered: false, persisted: false, duplicate: true }); expect(otherProject).toMatchObject({ delivered: true, persisted: false }); expect(send).toHaveBeenCalledTimes(2); expect(readMonitoringHistory('p1')).toHaveLength(0); });
  it.each([['daily', 86_400_001], ['weekly', 7 * 86_400_000 + 1]] as const)('expires the %s type cache after its current window', (frequency, elapsed) => { vi.useFakeTimers(); const start = new Date('2026-01-01T00:00:00Z'); vi.setSystemTime(start); const settings = { ...defaultMonitoringAlertSettings(), enabled: true, frequency }; const first = { type: 'crawl', fingerprint: `expiry-${frequency}-one`, occurredAt: start.toISOString() } as MonitoringAlert; const project = `expiry-${frequency}`; const reservation = reserveMonitoringAlert(project, first, settings); expect(reservation?.duplicate).toBe(false); expect(reservation?.finish(true)).toBe(true); vi.advanceTimersByTime(elapsed); const next = reserveMonitoringAlert(project, { ...first, fingerprint: `expiry-${frequency}-two` }, settings); expect(next?.duplicate).toBe(false); next?.finish(false); });
  it('re-evaluates the type cache when settings change frequency', () => { vi.useFakeTimers(); const start = new Date('2026-01-01T00:00:00Z'); vi.setSystemTime(start); const daily = { ...defaultMonitoringAlertSettings(), enabled: true, frequency: 'daily' as const }; const first = { type: 'semantic', fingerprint: 'frequency-switch-one', occurredAt: start.toISOString() } as MonitoringAlert; const project = 'frequency-switch'; reserveMonitoringAlert(project, first, daily)?.finish(true); vi.advanceTimersByTime(2 * 86_400_000); const weekly = { ...daily, frequency: 'weekly' as const }; expect(reserveMonitoringAlert(project, { ...first, fingerprint: 'frequency-switch-two' }, weekly)?.duplicate).toBe(true); const next = reserveMonitoringAlert(project, { ...first, fingerprint: 'frequency-switch-three' }, daily); expect(next?.duplicate).toBe(false); next?.finish(false); });
  it('keeps a delivered fingerprint deduplicated after a failed write', () => { vi.useFakeTimers(); const start = new Date('2026-01-01T00:00:00Z'); vi.setSystemTime(start); const settings = { ...defaultMonitoringAlertSettings(), enabled: true, frequency: 'daily' as const }; const alert = { type: 'pagespeed', fingerprint: 'fingerprint-cache', occurredAt: start.toISOString() } as MonitoringAlert; const write = vi.spyOn(Storage.prototype, 'setItem').mockImplementation(() => { throw new Error('quota'); }); const reservation = reserveMonitoringAlert('fingerprint-cache', alert, settings); expect(reservation?.finish(true)).toBe(false); write.mockRestore(); vi.advanceTimersByTime(30 * 86_400_000); expect(reserveMonitoringAlert('fingerprint-cache', alert, settings)?.duplicate).toBe(true); });
  it('uses a configured email adapter when desktop delivery is unavailable', async () => { send.mockResolvedValue(false); const alert = { type: 'gsc', sourceId: 'new', title: 'x', body: 'y', occurredAt: '2026-01-08T00:00:00Z', partial: false, evidence: {}, fingerprint: 'email' } as MonitoringAlert; const email = vi.fn().mockResolvedValue(true); saveMonitoringSettings('p1', { enabled: true }); expect((await deliverMonitoringAlert('p1', alert, { email })).delivered).toBe(true); expect(email).toHaveBeenCalledOnce(); });
});
