

import { CrawlConfigSchema } from '@/services/contracts/crawl';
import { readStorage } from '@/services/storage';
import { emptyAiResearchSettings } from '@/services/aiResearchEvidence';

import type { ToolsState } from './contracts';
import { domainQueryKey, backlinkQueryKey, activeProjectId } from './storageKeys';

import { loadDomainComparisonTargets, loadDomainComparisonHistory, loadLatestDomainComparison, loadDomainOverview, loadBacklinkProfile, loadBacklinkProfileHistory, loadBacklinkGapReport } from './researchPersistence';
import { gscClientIdKey, gscPropertyKey, DEFAULT_GSC_FILTERS, readGscFilters, loadProjectQuery, loadKeywordQuery, loadKeywordCountry, loadKeywordLanguage, loadDomainCountry, loadDomainLanguage, loadBacklinkGapSettings } from './projectPreferences';
import { DEFAULT_CRAWL_CONFIG, loadCrawlRequestProfiles } from './crawlPersistence';
import { loadSavedKeywords, loadTrackedRanks, loadRankTrackingDraft } from './keywordPersistence';
export const createToolsInitialState = (): Pick<ToolsState, "keywordQuery" | "keywordCountry" | "keywordLanguage" | "keywordResults" | "keywordResultsSource" | "isKeywordLoading" | "keywordError" | "savedKeywords" | "selectedTagFilter" | "trackedRanks" | "rankTrackingDraft" | "isRankLoading" | "rankError" | "domainQuery" | "domainCountry" | "domainLanguage" | "domainOverview" | "isDomainLoading" | "domainError" | "domainComparison" | "domainComparisonHistory" | "domainComparisonTargets" | "isDomainComparisonLoading" | "domainComparisonError" | "backlinkQuery" | "backlinkProfile" | "backlinkProfileHistory" | "isBacklinkLoading" | "backlinkError" | "backlinkGapCompetitors" | "backlinkGapIncludeSubdomains" | "backlinkGapReport" | "isBacklinkGapLoading" | "backlinkGapError" | "crawlUrl" | "crawlLimit" | "crawlResult" | "crawlRuns" | "isCrawling" | "isCrawlPaused" | "crawlProgress" | "crawlProgressDetail" | "interruptedCrawl" | "crawlConfig" | "crawlRequestProfiles" | "isSavingCrawlRequestProfile" | "isCheckingCrawlExternalLinks" | "crawlExternalLinkCheckProgress" | "crawlExternalLinkCheckError" | "activeCrawlRunId" | "selectedCrawlRunId" | "crawlError" | "crawlPersistenceError" | "crawlPersistenceNotice" | "crawlPersistenceCompacted" | "isRetryingCrawlPersistence" | "aiResearchSettings" | "aiBrandQuery" | "aiBrandDomain" | "aiBrandReport" | "aiBrandHistory" | "isAiBrandLoading" | "aiBrandError" | "aiSearchPrompt" | "aiPromptComparison" | "aiPromptHistory" | "isAiPromptLoading" | "aiPromptError" | "isGscConnected" | "gscClientId" | "gscClientSecret" | "gscProperties" | "gscProperty" | "gscFilters" | "gscData" | "gscDataFetchedAt" | "gscInspectionResult" | "isGscLoading" | "gscError" | "mcpClientTab"> => ({
keywordQuery: activeProjectId() ? loadKeywordQuery(activeProjectId()!) : '',
keywordCountry: activeProjectId() ? loadKeywordCountry(activeProjectId()!) : 'US',
keywordLanguage: activeProjectId() ? loadKeywordLanguage(activeProjectId()!) : 'en',
keywordResults: [],
keywordResultsSource: null,
isKeywordLoading: false,
keywordError: null,
savedKeywords: loadSavedKeywords(),
selectedTagFilter: null,
trackedRanks: loadTrackedRanks(),
rankTrackingDraft: loadRankTrackingDraft(),
isRankLoading: false,
rankError: null,
domainQuery: activeProjectId() ? loadProjectQuery(domainQueryKey, activeProjectId()!) : '',
domainCountry: activeProjectId() ? loadDomainCountry(activeProjectId()!) : 'US',
domainLanguage: activeProjectId() ? loadDomainLanguage(activeProjectId()!) : 'en',
domainOverview: activeProjectId() ? loadDomainOverview(activeProjectId()!) : null,
isDomainLoading: false,
domainError: null,
domainComparison: activeProjectId() ? loadLatestDomainComparison(activeProjectId()!) : null,
domainComparisonHistory: activeProjectId() ? loadDomainComparisonHistory(activeProjectId()!) : [],
domainComparisonTargets: activeProjectId() ? loadDomainComparisonTargets(activeProjectId()!) : [],
isDomainComparisonLoading: false,
domainComparisonError: null,
backlinkQuery: activeProjectId() ? loadProjectQuery(backlinkQueryKey, activeProjectId()!) : '',
backlinkProfile: activeProjectId() ? loadBacklinkProfile(activeProjectId()!) : null,
backlinkProfileHistory: activeProjectId() ? loadBacklinkProfileHistory(activeProjectId()!) : [],
isBacklinkLoading: false,
backlinkError: null,
backlinkGapCompetitors: activeProjectId() ? loadBacklinkGapSettings(activeProjectId()!).competitors : [],
backlinkGapIncludeSubdomains: activeProjectId() ? loadBacklinkGapSettings(activeProjectId()!).includeSubdomains : true,
backlinkGapReport: activeProjectId() ? loadBacklinkGapReport(activeProjectId()!) : null,
isBacklinkGapLoading: false,
backlinkGapError: null,
crawlUrl: '',
crawlLimit: 25,
crawlResult: null,
crawlRuns: [],
isCrawling: false,
isCrawlPaused: false,
crawlProgress: 0,
crawlProgressDetail: null,
interruptedCrawl: null,
crawlConfig: CrawlConfigSchema.parse(DEFAULT_CRAWL_CONFIG),
crawlRequestProfiles: loadCrawlRequestProfiles(),
isSavingCrawlRequestProfile: false,
isCheckingCrawlExternalLinks: false,
crawlExternalLinkCheckProgress: null,
crawlExternalLinkCheckError: null,
activeCrawlRunId: null,
selectedCrawlRunId: null,
crawlError: null,
crawlPersistenceError: null,
crawlPersistenceNotice: null,
crawlPersistenceCompacted: false,
isRetryingCrawlPersistence: false,
aiResearchSettings: emptyAiResearchSettings(),
aiBrandQuery: '',
aiBrandDomain: '',
aiBrandReport: null,
aiBrandHistory: [],
isAiBrandLoading: false,
aiBrandError: null,
aiSearchPrompt: '',
aiPromptComparison: null,
aiPromptHistory: [],
isAiPromptLoading: false,
aiPromptError: null,
isGscConnected: false,
gscClientId: activeProjectId() ? readStorage(gscClientIdKey(activeProjectId()!)) || '' : '',
gscClientSecret: '',
gscProperties: [],
gscProperty: activeProjectId() ? readStorage(gscPropertyKey(activeProjectId()!)) || '' : '',
gscFilters: activeProjectId() ? readGscFilters(activeProjectId()!) : { ...DEFAULT_GSC_FILTERS },
gscData: null,
gscDataFetchedAt: null,
gscInspectionResult: null,
isGscLoading: false,
gscError: null,
mcpClientTab: 'claude'
});
