import { Database, Search, TrendingUp, Shield, Globe2, Layers } from 'lucide-react';
import { TFunction } from 'i18next';

export const getBuiltInTools = (t: TFunction) => [
  {
    id: 'seomi_gsc_search_analytics',
    name: 'seomi_gsc_search_analytics',
    description: t('mcp.toolDesc_seomi_gsc_search_analytics'),
    input: 'site_url, start_date, end_date, dimensions?, type?, row_limit?, start_row?',
    icon: Database,
  },
  {
    id: 'seomi_gsc_url_inspection',
    name: 'seomi_gsc_url_inspection',
    description: t('mcp.toolDesc_seomi_gsc_url_inspection'),
    input: 'inspection_url, site_url, language_code?',
    icon: Database,
  },
  {
    id: 'seomi_research_keywords',
    name: 'seomi_research_keywords',
    description: t('mcp.toolDesc_seomi_research_keywords'),
    input: 'keyword, location_code?, language_code?',
    icon: Search,
  },
  {
    id: 'seomi_research_keyword_suggestions',
    name: 'seomi_research_keyword_suggestions',
    description: t('mcp.toolDesc_seomi_research_keyword_suggestions'),
    input: 'seed, location_code?, language_code?',
    icon: Search,
  },
  {
    id: 'seomi_research_serp',
    name: 'seomi_research_serp',
    description: t('mcp.toolDesc_seomi_research_serp'),
    input: 'keyword, location_code?, language_code?, depth?',
    icon: Search,
  },
  {
    id: 'seomi_track_rank',
    name: 'seomi_track_rank',
    description: t('mcp.toolDesc_seomi_track_rank'),
    input: 'keyword, target, location_code?, language_code?, depth?',
    icon: TrendingUp,
  },
  {
    id: 'seomi_research_backlinks',
    name: 'seomi_research_backlinks',
    description: t('mcp.toolDesc_seomi_research_backlinks'),
    input: 'target',
    icon: Shield,
  },
  {
    id: 'seomi_research_backlink_anchors',
    name: 'seomi_research_backlink_anchors',
    description: t('mcp.toolDesc_seomi_research_backlink_anchors'),
    input: 'target, offset?, limit?',
    icon: Shield,
  },
  {
    id: 'seomi_research_backlink_pages',
    name: 'seomi_research_backlink_pages',
    description: t('mcp.toolDesc_seomi_research_backlink_pages'),
    input: 'target, offset?, limit?',
    icon: Shield,
  },
  {
    id: 'seomi_research_backlink_gap',
    name: 'seomi_research_backlink_gap',
    description: t('mcp.toolDesc_seomi_research_backlink_gap'),
    input: 'target, competitors, include_subdomains?, offset?, limit?',
    icon: Shield,
  },
  {
    id: 'seomi_research_domain_overview',
    name: 'seomi_research_domain_overview',
    description: t('mcp.toolDesc_seomi_research_domain_overview'),
    input: 'target, location_code?, language_code?',
    icon: Globe2,
  },
  {
    id: 'seomi_research_top_pages',
    name: 'seomi_research_top_pages',
    description: t('mcp.toolDesc_seomi_research_top_pages'),
    input: 'target, location_code?, language_code?, limit?',
    icon: Globe2,
  },
  {
    id: 'seomi_research_ranked_keywords',
    name: 'seomi_research_ranked_keywords',
    description: t('mcp.toolDesc_seomi_research_ranked_keywords'),
    input: 'target, location_code?, language_code?, limit?',
    icon: Globe2,
  },
  {
    id: 'seomi_research_domain_competitors',
    name: 'seomi_research_domain_competitors',
    description: t('mcp.toolDesc_seomi_research_domain_competitors'),
    input: 'target, location_code?, language_code?, limit?',
    icon: Globe2,
  },
  {
    id: 'seomi_audit_url',
    name: 'seomi_audit_url',
    description: t('mcp.toolDesc_seomi_audit_url'),
    input: 'url, timeout_ms?',
    icon: Layers,
  },
  {
    id: 'seomi_crawl_site',
    name: 'seomi_crawl_site',
    description: t('mcp.toolDesc_seomi_crawl_site'),
    input: 'start_url, max_pages?, max_depth?, timeout_ms?, scope_host?, allow_subdomains?',
    icon: Layers,
  },
  {
    id: 'seomi_pagespeed_insights',
    name: 'seomi_pagespeed_insights',
    description: t('mcp.toolDesc_seomi_pagespeed_insights'),
    input: 'url, strategy?, categories?',
    icon: TrendingUp,
  },
  {
    id: 'seomi_crux',
    name: 'seomi_crux',
    description: t('mcp.toolDesc_seomi_crux'),
    input: 'url, form_factor?',
    icon: TrendingUp,
  },
];
