use super::super::{
    content_metrics::ContentMetrics,
    fetch_types::FetchedPageData,
    models::{
        semantic_content_is_partial, semantic_provenance_for_mode, CrawledImage, CrawledPageIssue,
        CrawledPageSummary,
    },
};
use super::page_content::PageContentOutcome;
use super::page_extra::PageExtraOutcome;
use super::page_links::PageLinksOutcome;
use super::page_metadata::PageMetadataOutcome;

#[allow(clippy::too_many_arguments)]
pub fn build_crawled_page_summary(
    final_url: String,
    redirect_chain: Vec<super::super::models::CrawledRedirectHop>,
    redirect_stopped_reason: Option<String>,
    page_data: &FetchedPageData,
    page_duration: u64,
    current_url: &str,
    depth: usize,
    crawl_mode: &str,
    detected_charset: Option<String>,
    cm: &ContentMetrics,
    focus_phrase: Option<crate::commands::site_crawler::models::CrawledFocusPhraseEvidence>,
    extra: PageExtraOutcome,
    content: PageContentOutcome,
    meta: PageMetadataOutcome,
    links: PageLinksOutcome,
    images: Vec<CrawledImage>,
    discovery_sources: Vec<crate::commands::site_crawler::models::CrawledDiscoverySource>,
    issues: Vec<CrawledPageIssue>,
) -> CrawledPageSummary {
    let semantic_content_partial = semantic_content_is_partial(
        page_data.body_truncated,
        page_data.body_read_failed,
        content.semantic_terms.len(),
        content.semantic_excerpts.len(),
        links.semantic_links.len(),
    );
    let semantic_content_provenance =
        semantic_provenance_for_mode(crawl_mode, &content.semantic_content_source);
    let issues_count = issues.len();

    CrawledPageSummary {
        url: current_url.to_string(),
        final_url,
        discovery_sources,
        redirect_chain,
        redirect_stop_reason: redirect_stopped_reason,
        depth,
        http_status: page_data.status,
        response_time_ms: page_duration,
        rendered_lcp_ms: page_data.rendered_lcp_ms,
        rendered_inp_ms: page_data.rendered_inp_ms,
        rendered_cls: page_data.rendered_cls,
        request_error_kind: None,
        title: content.title,
        title_length: content.title_length,
        meta_description: content.meta_description,
        meta_description_length: content.meta_description_length,
        canonical: meta.canonical,
        canonical_targets: meta.canonical_targets,
        canonical_declaration_count: meta.canonical_declaration_count,
        canonical_relation: meta.canonical_relation,
        canonical_robots_conflict: meta.canonical_robots_conflict,
        client_redirects: meta.client_redirects,
        meta_robots: meta.meta_robots,
        x_robots_tag: meta.x_robots_tag,
        robots_decision: meta.robots_decision,
        indexability_verdict: meta.indexability_verdict,
        indexability_status: meta.indexability_status,
        content_type: page_data.content_type.clone(),
        content_length: page_data.content_length,
        content_encoding: page_data.content_encoding.clone(),
        charset: page_data.charset.clone(),
        detected_charset,
        cache_control: page_data.cache_control.clone(),
        body_truncated: page_data.body_truncated,
        word_count: content.word_count,
        text_ratio_percent: content.text_ratio_percent,
        reading_time_minutes: content.reading_time_minutes,
        sentence_count: cm.sentence_count,
        average_words_per_sentence: cm.average_words_per_sentence,
        average_characters_per_word: cm.average_characters_per_word,
        complexity_score: cm.complexity_score,
        complexity_label: cm.complexity_label.clone(),
        readability_ease_score: cm.readability_ease_score,
        readability_grade: cm.readability_grade,
        readability_method: cm.readability_method.clone(),
        readability_label: cm.readability_label.clone(),
        content_terms: cm.content_terms.clone(),
        focus_phrase,
        content_hash: content.content_hash,
        content_simhash: content.content_simhash,
        semantic_terms: content.semantic_terms,
        semantic_excerpts: content.semantic_excerpts,
        semantic_links: links.semantic_links,
        semantic_content_source: content.semantic_content_source,
        semantic_content_provenance,
        semantic_content_partial,
        schema_types: extra.schema_types,
        schema_references: extra.schema_references,
        schema_syntax_errors: extra.schema_syntax_errors,
        schema_validation_findings: extra.schema_validation_findings,
        schema_validation_truncated: extra.schema_validation_truncated,
        html_validation_findings: extra.html_validation_findings,
        html_validation_truncated: extra.html_validation_truncated,
        document_language: content.document_language,
        hreflangs: extra.hreflangs,
        amp_url: extra.amp_url,
        amp_target_http_status: None,
        amp_target_checked_in_run: false,
        amp_target_canonical_alignment: None,
        h1_count: content.h1_count,
        heading_counts: content.heading_counts,
        duplicate_headings: content.duplicate_headings,
        pagination_next: extra.pagination_next,
        pagination_prev: extra.pagination_prev,
        pagination_links: extra.pagination_links,
        pagination_declaration_count: extra.pagination_declaration_count,
        pagination_invalid_declaration_count: extra.pagination_invalid_declaration_count,
        pagination_canonical_alignment: meta.pagination_canonical_alignment,
        internal_link_count: links.internal_link_count,
        external_link_count: links.external_link_count,
        links: links.links,
        images,
        frames: extra.frames,
        frames_truncated: extra.frames_truncated,
        favicons: extra.favicons,
        favicon_metadata: extra.favicon_metadata,
        favicon_resource_checks: extra.favicon_resource_checks,
        social_meta_tags: extra.social_meta_tags,
        custom_search_results: extra.custom_search_results,
        issues_count,
        issues,
    }
}
