import type { CatalogTuple } from './catalogTypes';

export const CATALOG: CatalogTuple[] = [
  [2008, 'Albania', 'AL', 'Country', 'Albanian', 'sq', 'google'],
  [2012, 'Algeria', 'DZ', 'Country', 'French', 'fr', 'google'],
  [2012, 'Algeria', 'DZ', 'Country', 'Arabic', 'ar', 'google'],
  [2024, 'Angola', 'AO', 'Country', 'Portuguese', 'pt', 'google'],
  [2031, 'Azerbaijan', 'AZ', 'Country', 'Azeri', 'az', 'google'],
  [2032, 'Argentina', 'AR', 'Country', 'Spanish', 'es', 'google'],
  [2036, 'Australia', 'AU', 'Country', 'English', 'en', 'google'],
  [2040, 'Austria', 'AT', 'Country', 'German', 'de', 'google'],
  [2048, 'Bahrain', 'BH', 'Country', 'Arabic', 'ar', 'google'],
  [2050, 'Bangladesh', 'BD', 'Country', 'Bengali', 'bn', 'google'],
  [2051, 'Armenia', 'AM', 'Country', 'Armenian', 'hy', 'google'],
  [2056, 'Belgium', 'BE', 'Country', 'French', 'fr', 'google'],
  [2056, 'Belgium', 'BE', 'Country', 'Dutch', 'nl', 'google'],
  [2056, 'Belgium', 'BE', 'Country', 'German', 'de', 'google'],
  [2068, 'Bolivia', 'BO', 'Country', 'Spanish', 'es', 'google'],
  [2070, 'Bosnia and Herzegovina', 'BA', 'Country', 'Bosnian', 'bs', 'google'],
  [2076, 'Brazil', 'BR', 'Country', 'Portuguese', 'pt', 'google'],
  [2100, 'Bulgaria', 'BG', 'Country', 'Bulgarian', 'bg', 'google'],
  [2104, 'Myanmar (Burma)', 'MM', 'Country', 'English', 'en', 'google'],
  [2116, 'Cambodia', 'KH', 'Country', 'English', 'en', 'google'],
  [2120, 'Cameroon', 'CM', 'Country', 'French', 'fr', 'google'],
  [2124, 'Canada', 'CA', 'Country', 'English', 'en', 'google'],
  [2124, 'Canada', 'CA', 'Country', 'French', 'fr', 'google'],
  [2144, 'Sri Lanka', 'LK', 'Country', 'English', 'en', 'google'],
  [2152, 'Chile', 'CL', 'Country', 'Spanish', 'es', 'google'],
  [2158, 'Taiwan', 'TW', 'Region', 'Chinese (Traditional)', 'zh-TW', 'google'],
  [2170, 'Colombia', 'CO', 'Country', 'Spanish', 'es', 'google'],
  [2188, 'Costa Rica', 'CR', 'Country', 'Spanish', 'es', 'google'],
  [2191, 'Croatia', 'HR', 'Country', 'Croatian', 'hr', 'google'],
  [2196, 'Cyprus', 'CY', 'Country', 'Greek', 'el', 'google'],
  [2196, 'Cyprus', 'CY', 'Country', 'English', 'en', 'google'],
  [2203, 'Czechia', 'CZ', 'Country', 'Czech', 'cs', 'google'],
  [2208, 'Denmark', 'DK', 'Country', 'Danish', 'da', 'google'],
  [2218, 'Ecuador', 'EC', 'Country', 'Spanish', 'es', 'google'],
  [2222, 'El Salvador', 'SV', 'Country', 'Spanish', 'es', 'google'],
  [2233, 'Estonia', 'EE', 'Country', 'Estonian', 'et', 'google'],
  [2246, 'Finland', 'FI', 'Country', 'Finnish', 'fi', 'google'],
  [2250, 'France', 'FR', 'Country', 'French', 'fr', 'google'],
  [2276, 'Germany', 'DE', 'Country', 'German', 'de', 'google'],
  [2288, 'Ghana', 'GH', 'Country', 'English', 'en', 'google'],
  [2300, 'Greece', 'GR', 'Country', 'Greek', 'el', 'google'],
  [2300, 'Greece', 'GR', 'Country', 'English', 'en', 'google'],
  [2320, 'Guatemala', 'GT', 'Country', 'Spanish', 'es', 'google'],
  [2344, 'Hong Kong', 'HK', 'Region', 'English', 'en', 'google'],
  [2344, 'Hong Kong', 'HK', 'Region', 'Chinese (Traditional)', 'zh-TW', 'google'],
  [2348, 'Hungary', 'HU', 'Country', 'Hungarian', 'hu', 'google'],
  [2356, 'India', 'IN', 'Country', 'English', 'en', 'google'],
  [2356, 'India', 'IN', 'Country', 'Hindi', 'hi', 'google'],
  [2360, 'Indonesia', 'ID', 'Country', 'English', 'en', 'google'],
  [2360, 'Indonesia', 'ID', 'Country', 'Indonesian', 'id', 'google'],
  [2372, 'Ireland', 'IE', 'Country', 'English', 'en', 'google'],
  [2376, 'Israel', 'IL', 'Country', 'Hebrew', 'he', 'google'],
  [2376, 'Israel', 'IL', 'Country', 'Arabic', 'ar', 'google'],
  [2380, 'Italy', 'IT', 'Country', 'Italian', 'it', 'google'],
  [2384, "Cote d'Ivoire", 'CI', 'Country', 'French', 'fr', 'google'],
  [2392, 'Japan', 'JP', 'Country', 'Japanese', 'ja', 'google'],
  [2398, 'Kazakhstan', 'KZ', 'Country', 'Russian', 'ru', 'google'],
  [2400, 'Jordan', 'JO', 'Country', 'Arabic', 'ar', 'google'],
  [2404, 'Kenya', 'KE', 'Country', 'English', 'en', 'google'],
  [2410, 'South Korea', 'KR', 'Country', 'Korean', 'ko', 'google'],
  [2428, 'Latvia', 'LV', 'Country', 'Latvian', 'lv', 'google'],
  [2440, 'Lithuania', 'LT', 'Country', 'Lithuanian', 'lt', 'google'],
  [2458, 'Malaysia', 'MY', 'Country', 'English', 'en', 'google'],
  [2458, 'Malaysia', 'MY', 'Country', 'Malay', 'ms', 'google'],
  [2470, 'Malta', 'MT', 'Country', 'English', 'en', 'google'],
  [2484, 'Mexico', 'MX', 'Country', 'Spanish', 'es', 'google'],
  [2492, 'Monaco', 'MC', 'Country', 'French', 'fr', 'google'],
  [2498, 'Moldova', 'MD', 'Country', 'Romanian', 'ro', 'google'],
  [2504, 'Morocco', 'MA', 'Country', 'Arabic', 'ar', 'google'],
  [2504, 'Morocco', 'MA', 'Country', 'French', 'fr', 'google'],
  [2528, 'Netherlands', 'NL', 'Country', 'Dutch', 'nl', 'google'],
  [2554, 'New Zealand', 'NZ', 'Country', 'English', 'en', 'google'],
  [2558, 'Nicaragua', 'NI', 'Country', 'Spanish', 'es', 'google'],
  [2566, 'Nigeria', 'NG', 'Country', 'English', 'en', 'google'],
  [2578, 'Norway', 'NO', 'Country', 'Norwegian (Bokmål)', 'nb', 'google'],
  [2586, 'Pakistan', 'PK', 'Country', 'English', 'en', 'google'],
  [2586, 'Pakistan', 'PK', 'Country', 'Urdu', 'ur', 'google'],
  [2591, 'Panama', 'PA', 'Country', 'Spanish', 'es', 'google'],
  [2600, 'Paraguay', 'PY', 'Country', 'Spanish', 'es', 'google'],
  [2604, 'Peru', 'PE', 'Country', 'Spanish', 'es', 'google'],
  [2608, 'Philippines', 'PH', 'Country', 'English', 'en', 'google'],
  [2608, 'Philippines', 'PH', 'Country', 'Tagalog', 'tl', 'google'],
  [2616, 'Poland', 'PL', 'Country', 'Polish', 'pl', 'google'],
  [2620, 'Portugal', 'PT', 'Country', 'Portuguese', 'pt', 'google'],
  [2642, 'Romania', 'RO', 'Country', 'Romanian', 'ro', 'google'],
  [2682, 'Saudi Arabia', 'SA', 'Country', 'Arabic', 'ar', 'google,amazon'],
  [2686, 'Senegal', 'SN', 'Country', 'French', 'fr', 'google'],
  [2688, 'Serbia', 'RS', 'Country', 'Serbian', 'sr', 'google'],
  [2702, 'Singapore', 'SG', 'Country', 'English', 'en', 'google'],
  [2702, 'Singapore', 'SG', 'Country', 'Chinese (Simplified)', 'zh-CN', 'google'],
  [2703, 'Slovakia', 'SK', 'Country', 'Slovak', 'sk', 'google'],
  [2704, 'Vietnam', 'VN', 'Country', 'English', 'en', 'google'],
  [2704, 'Vietnam', 'VN', 'Country', 'Vietnamese', 'vi', 'google'],
  [2705, 'Slovenia', 'SI', 'Country', 'Slovenian', 'sl', 'google'],
  [2710, 'South Africa', 'ZA', 'Country', 'English', 'en', 'google'],
  [2724, 'Spain', 'ES', 'Country', 'Spanish', 'es', 'google'],
  [2752, 'Sweden', 'SE', 'Country', 'Swedish', 'sv', 'google'],
  [2756, 'Switzerland', 'CH', 'Country', 'German', 'de', 'google'],
  [2756, 'Switzerland', 'CH', 'Country', 'French', 'fr', 'google'],
  [2756, 'Switzerland', 'CH', 'Country', 'Italian', 'it', 'google'],
  [2764, 'Thailand', 'TH', 'Country', 'Thai', 'th', 'google'],
  [2784, 'United Arab Emirates', 'AE', 'Country', 'Arabic', 'ar', 'google,amazon'],
  [2784, 'United Arab Emirates', 'AE', 'Country', 'English', 'en', 'google'],
  [2788, 'Tunisia', 'TN', 'Country', 'Arabic', 'ar', 'google'],
  [2792, 'Turkiye', 'TR', 'Country', 'Turkish', 'tr', 'google'],
  [2804, 'Ukraine', 'UA', 'Country', 'Ukrainian', 'uk', 'google'],
  [2804, 'Ukraine', 'UA', 'Country', 'Russian', 'ru', 'google'],
  [2807, 'North Macedonia', 'MK', 'Country', 'Macedonian', 'mk', 'google'],
  [2818, 'Egypt', 'EG', 'Country', 'Arabic', 'ar', 'google,amazon'],
  [2818, 'Egypt', 'EG', 'Country', 'English', 'en', 'google'],
  [2826, 'United Kingdom', 'GB', 'Country', 'English', 'en', 'google'],
  [2840, 'United States', 'US', 'Country', 'English', 'en', 'google,bing,amazon'],
  [2840, 'United States', 'US', 'Country', 'Spanish', 'es', 'google'],
  [2854, 'Burkina Faso', 'BF', 'Country', 'French', 'fr', 'google'],
  [2858, 'Uruguay', 'UY', 'Country', 'Spanish', 'es', 'google'],
  [2862, 'Venezuela', 'VE', 'Country', 'Spanish', 'es', 'google'],
];
