import type { CrawlConfig } from '@/types';

export const DEFAULT_CRAWL_CONFIG: CrawlConfig = {
  crawlMode: 'http',
  renderWaitForSelector: '',
  renderWaitDelayMs: 0,
  renderLazyScrollCycles: 0,
  includePatterns: [],
  excludePatterns: [],
  allowSubdomains: false,
  allowedHosts: [],
  scopePath: undefined,
  keepQueryStrings: false,
  respectRobots: true,
  respectCrawlDelay: true,
  discoverSitemaps: true,
  maxRedirects: 10,
  followNofollow: false,
  maxResponseBytes: 5_000_000,
  maxRunSeconds: 300,
  requestTimeoutSecs: undefined,
  verifySsl: true,
  seedUrls: [],
  listMode: false,
  userAgent: '',
  requestProfileId: undefined,
  trimTrailingSlash: false,
  lowercasePath: false,
  stripTrackingParameters: false,
  allowedQueryParameters: [],
  deniedQueryParameters: [],
  customSearches: [],
  focusPhrase: '',
  crawlImages: false,
  crawlStylesheets: false,
  crawlScripts: false,
  crawlOtherResources: false,
  maxResourceRequests: 250,
  maxConcurrentRequests: 4,
};

