import type { CrawlRunRecord } from '@/types';

/**
 * Reduce only verbose, repeatable evidence as a last-resort persistence
 * fallback. The in-memory result is never changed; a user can still inspect
 * the complete run until restart, while the persisted snapshot advertises its
 * bounded state through `storage_compacted` instead of failing the whole crawl.
 */
export const compactCrawlRunsForStorage = (runs: CrawlRunRecord[], level: 1 | 2 | 3 = 1): CrawlRunRecord[] => {
  const cloned = JSON.parse(JSON.stringify(runs)) as CrawlRunRecord[];
  const perPage = level === 1 ? 40 : level === 2 ? 10 : 0;
  const perPageIssues = level === 1 ? 40 : level === 2 ? 10 : 4;
  const perPageExcerpts = level === 1 ? 10 : level === 2 ? 3 : 0;
  return cloned.map((run) => {
    run.storage_compacted = true;
    const pages = Array.isArray(run.result.pages) ? run.result.pages : [];
    run.result.pages = pages.map((page) => ({
      ...page,
      links: (page.links || []).slice(0, level === 3 ? 10 : perPage),
      images: (page.images || []).slice(0, level === 3 ? 10 : perPage),
      semantic_links: page.semantic_links?.slice(0, perPage),
      semantic_excerpts: page.semantic_excerpts?.slice(0, perPageExcerpts),
      issues: (page.issues || []).slice(0, perPageIssues),
      html_validation_findings: page.html_validation_findings?.slice(0, perPageIssues).map((finding) => ({ ...finding, source_excerpt: undefined })),
      schema_validation_findings: page.schema_validation_findings?.slice(0, perPageIssues),
      custom_search_results: page.custom_search_results?.slice(0, perPage),
      content_terms: page.content_terms?.slice(0, level === 1 ? 20 : level === 2 ? 8 : 3),
      hreflangs: page.hreflangs?.slice(0, level === 1 ? 40 : level === 2 ? 12 : 4),
      canonical_targets: page.canonical_targets?.slice(0, level === 1 ? 20 : level === 2 ? 6 : 2),
      pagination_links: page.pagination_links?.slice(0, level === 1 ? 20 : level === 2 ? 6 : 2),
      schema_references: page.schema_references?.slice(0, level === 1 ? 40 : level === 2 ? 12 : 4),
      favicon_metadata: page.favicon_metadata?.slice(0, level === 1 ? 20 : level === 2 ? 6 : 2),
      favicon_resource_checks: page.favicon_resource_checks?.slice(0, level === 1 ? 20 : level === 2 ? 6 : 2),
      social_meta_tags: page.social_meta_tags?.slice(0, level === 1 ? 40 : level === 2 ? 12 : 4),
      frames: page.frames?.slice(0, level === 1 ? 20 : level === 2 ? 6 : 2),
      discovery_sources: page.discovery_sources?.slice(0, level === 1 ? 20 : level === 2 ? 6 : 2),
    }));
    if (level >= 2) {
      run.result.resources = undefined;
      run.result.sitemap_urls = (run.result.sitemap_urls || []).slice(0, level === 2 ? 500 : 100);
    } else {
      run.result.resources = run.result.resources?.slice(0, 2_000);
    }
    if (level === 3) {
      // Keep the crawl navigable while removing the large, repeatable payloads
      // that can make a single rendered run exceed a WebView quota.
      run.result.pages = run.result.pages.map((page) => ({
        ...page,
        // Preserve enough evidence to identify a problem, but never retain
        // source snippets or per-resource diagnostics in the last bounded
        // retry. Those fields are the dominant source of multi-page quota
        // failures and can be regenerated by running the crawl again.
        links: page.links.slice(0, 10).map((link) => ({
          target_url: link.target_url,
          anchor_text: link.anchor_text,
          rel: link.rel,
          is_internal: link.is_internal,
          target_http_status: link.target_http_status,
          target_redirect_url: link.target_redirect_url,
        })),
        images: page.images.slice(0, 10).map((image) => ({
          src: image.src,
          alt: image.alt,
          format: image.format,
          width: image.width,
          height: image.height,
          dimensions_source: image.dimensions_source,
          lazy_loaded: image.lazy_loaded,
          checked_in_run: image.checked_in_run,
          http_status: image.http_status,
          content_length: image.content_length,
        })),
        semantic_terms: page.semantic_terms?.slice(0, 12),
        content_terms: page.content_terms?.slice(0, 3),
        issues: page.issues.slice(0, 4),
        semantic_excerpts: undefined,
        schema_references: undefined,
        custom_search_results: undefined,
        favicon_metadata: undefined,
        favicon_resource_checks: undefined,
        social_meta_tags: undefined,
        frames: undefined,
        discovery_sources: undefined,
      }));
      run.result.rejected_urls = (run.result.rejected_urls || []).slice(0, 100);
    }
    return run;
  });
};
