import { z } from 'zod';
import type { CustomSearchDefinition, CrawlConfig } from '@/types';

export const CustomSearchDefinitionSchema = z.object({
  id: z.string(),
  name: z.string(),
  selectorType: z.union([z.literal('css'), z.literal('xpath'), z.literal('regex')]),
  query: z.string(),
  resultType: z.union([z.literal('text'), z.literal('html'), z.literal('attribute')]),
  attribute: z.string().nullable().transform(value => value ?? undefined).optional(),
}).passthrough() satisfies z.ZodType<CustomSearchDefinition, z.ZodTypeDef, unknown>;

export const CrawlConfigSchema = z.object({
  crawlMode: z.union([z.literal('http'), z.literal('browser-rendered')]).nullable().transform(value => value ?? undefined).optional(),
  renderWaitForSelector: z.string().nullable().transform(value => value ?? undefined).optional(),
  renderWaitDelayMs: z.number().finite().nullable().transform(value => value ?? undefined).optional(),
  renderLazyScrollCycles: z.number().finite().nullable().transform(value => value ?? undefined).optional(),
  maxPages: z.number().finite().nullable().transform(value => value ?? undefined).optional(),
  maxDepth: z.number().finite().nullable().transform(value => value ?? undefined).optional(),
  includePatterns: z.array(z.string()),
  excludePatterns: z.array(z.string()),
  allowSubdomains: z.boolean(),
  allowedHosts: z.array(z.string()).nullable().transform(value => value ?? undefined).optional(),
  scopePath: z.string().nullable().transform(value => value ?? undefined).optional(),
  keepQueryStrings: z.boolean(),
  respectRobots: z.boolean(),
  respectCrawlDelay: z.boolean(),
  discoverSitemaps: z.boolean(),
  maxRedirects: z.number().finite().nullable().transform(value => value ?? undefined).optional(),
  followNofollow: z.boolean(),
  maxResponseBytes: z.number().finite().nullable().transform(value => value ?? undefined).optional(),
  maxRunSeconds: z.number().finite().nullable().transform(value => value ?? undefined).optional(),
  requestTimeoutSecs: z.number().finite().nullable().transform(value => value ?? undefined).optional(),
  verifySsl: z.boolean().nullable().transform(value => value ?? undefined).optional(),
  seedUrls: z.array(z.string()).nullable().transform(value => value ?? undefined).optional(),
  listMode: z.boolean().nullable().transform(value => value ?? undefined).optional(),
  userAgent: z.string().nullable().transform(value => value ?? undefined).optional(),
  requestProfileId: z.string().nullable().transform(value => value ?? undefined).optional(),
  trimTrailingSlash: z.boolean().nullable().transform(value => value ?? undefined).optional(),
  lowercasePath: z.boolean().nullable().transform(value => value ?? undefined).optional(),
  stripTrackingParameters: z.boolean().nullable().transform(value => value ?? undefined).optional(),
  allowedQueryParameters: z.array(z.string()).nullable().transform(value => value ?? undefined).optional(),
  deniedQueryParameters: z.array(z.string()).nullable().transform(value => value ?? undefined).optional(),
  customSearches: z.array(CustomSearchDefinitionSchema).nullable().transform(value => value ?? undefined).optional(),
  focusPhrase: z.string().nullable().transform(value => value ?? undefined).optional(),
  crawlImages: z.boolean().nullable().transform(value => value ?? undefined).optional(),
  crawlStylesheets: z.boolean().nullable().transform(value => value ?? undefined).optional(),
  crawlScripts: z.boolean().nullable().transform(value => value ?? undefined).optional(),
  crawlOtherResources: z.boolean().nullable().transform(value => value ?? undefined).optional(),
  maxResourceRequests: z.number().finite().nullable().transform(value => value ?? undefined).optional(),
  maxConcurrentRequests: z.number().finite().nullable().transform(value => value ?? undefined).optional(),
  resumeCompletedUrls: z.array(z.string()).nullable().transform(value => value ?? undefined).optional(),
  resumeFrontierUrls: z.array(z.string()).nullable().transform(value => value ?? undefined).optional(),
}).passthrough() satisfies z.ZodType<CrawlConfig, z.ZodTypeDef, unknown>;
