import { z } from 'zod';
import type { CrawledPageSummary, CrawledResource } from '@/types';
import {
  CrawledDiscoverySourceSchema,
  CrawledRedirectHopSchema,
  CrawledCanonicalTargetSchema,
  CrawledClientRedirectSchema,
  CrawledHreflangSchema,
  CrawledPaginationLinkSchema,
} from './crawlNavigation';
import {
  CrawledRobotsDecisionSchema,
  CrawledIndexabilityVerdictSchema,
  CrawledContentTermSchema,
  CrawledFocusPhraseEvidenceSchema,
  CrawledLinkSchema,
  CrawledSchemaReferenceSchema,
  CrawledSchemaFindingSchema,
  CrawledHtmlValidationFindingSchema,
  CrawledDuplicateHeadingSchema,
  CrawledPageIssueSchema,
  CrawledCustomSearchResultSchema,
} from './crawlFindings';
import {
  CrawledImageSchema,
  CrawledFrameSchema,
  FaviconDataSchema,
  CrawledSocialResourceCheckSchema,
  CrawledSocialMetaTagSchema,
} from './crawlMedia';

export const CrawledPageSummarySchema = z.object({
  url: z.string(),
  final_url: z.string(),
  discovery_sources: z.array(CrawledDiscoverySourceSchema).nullable().transform(value => value ?? undefined).optional(),
  redirect_chain: z.array(CrawledRedirectHopSchema),
  redirect_stop_reason: z.union([z.string(), z.null()]).optional(),
  depth: z.number().finite(),
  http_status: z.number().finite(),
  http_response_url: z.union([z.string(), z.null()]).optional(),
  response_url_mismatch: z.boolean().optional(),
  response_time_ms: z.number().finite(),
  rendered_lcp_ms: z.union([z.number().finite(), z.null()]).optional(),
  rendered_inp_ms: z.union([z.number().finite(), z.null()]).optional(),
  rendered_cls: z.union([z.number().finite(), z.null()]).optional(),
  request_error_kind: z.union([z.string(), z.null()]).optional(),
  title: z.union([z.string(), z.null()]).optional(),
  title_length: z.union([z.number().finite(), z.null()]).optional(),
  meta_description: z.union([z.string(), z.null()]).optional(),
  meta_description_length: z.union([z.number().finite(), z.null()]).optional(),
  canonical: z.union([z.string(), z.null()]).optional(),
  canonical_targets: z.array(CrawledCanonicalTargetSchema).nullable().transform(value => value ?? undefined).optional(),
  canonical_declaration_count: z.number().finite().nullable().transform(value => value ?? undefined).optional(),
  canonical_relation: z.string().nullable().transform(value => value ?? undefined).optional(),
  canonical_robots_conflict: z.boolean().nullable().transform(value => value ?? undefined).optional(),
  client_redirects: z.array(CrawledClientRedirectSchema).nullable().transform(value => value ?? undefined).optional(),
  meta_robots: z.union([z.string(), z.null()]).optional(),
  x_robots_tag: z.union([z.string(), z.null()]).optional(),
  robots_decision: z.union([CrawledRobotsDecisionSchema, z.null()]).optional(),
  indexability_verdict: z.union([CrawledIndexabilityVerdictSchema, z.null()]).optional(),
  indexability_status: z.string(),
  content_type: z.union([z.string(), z.null()]).optional(),
  content_length: z.union([z.number().finite(), z.null()]).optional(),
  content_encoding: z.union([z.string(), z.null()]).optional(),
  charset: z.union([z.string(), z.null()]).optional(),
  detected_charset: z.union([z.string(), z.null()]).optional(),
  cache_control: z.union([z.string(), z.null()]).optional(),
  body_truncated: z.boolean(),
  word_count: z.number().finite(),
  text_ratio_percent: z.union([z.number().finite(), z.null()]).optional(),
  reading_time_minutes: z.union([z.number().finite(), z.null()]).optional(),
  sentence_count: z.union([z.number().finite(), z.null()]).optional(),
  average_words_per_sentence: z.union([z.number().finite(), z.null()]).optional(),
  average_characters_per_word: z.union([z.number().finite(), z.null()]).optional(),
  complexity_score: z.union([z.number().finite(), z.null()]).optional(),
  complexity_label: z.union([z.string(), z.null()]).optional(),
  readability_ease_score: z.union([z.number().finite(), z.null()]).optional(),
  readability_grade: z.union([z.number().finite(), z.null()]).optional(),
  readability_method: z.union([z.string(), z.null()]).optional(),
  readability_label: z.union([z.string(), z.null()]).optional(),
  content_terms: z.array(CrawledContentTermSchema).nullable().transform(value => value ?? undefined).optional(),
  focus_phrase: z.union([CrawledFocusPhraseEvidenceSchema, z.null()]).optional(),
  content_hash: z.union([z.string(), z.null()]).optional(),
  content_simhash: z.union([z.string(), z.null()]).optional(),
  semantic_terms: z.array(z.string()).nullable().transform(value => value ?? undefined).optional(),
  semantic_excerpts: z.array(z.string()).nullable().transform(value => value ?? undefined).optional(),
  semantic_links: z.array(CrawledLinkSchema).nullable().transform(value => value ?? undefined).optional(),
  semantic_content_source: z.string().nullable().transform(value => value ?? undefined).optional(),
  semantic_content_provenance: z.string().nullable().transform(value => value ?? undefined).optional(),
  semantic_content_partial: z.boolean().nullable().transform(value => value ?? undefined).optional(),
  schema_types: z.array(z.string()),
  schema_references: z.array(CrawledSchemaReferenceSchema).nullable().transform(value => value ?? undefined).optional(),
  schema_syntax_errors: z.number().finite(),
  schema_validation_findings: z.array(CrawledSchemaFindingSchema).nullable().transform(value => value ?? undefined).optional(),
  schema_validation_truncated: z.boolean().nullable().transform(value => value ?? undefined).optional(),
  html_validation_findings: z.array(CrawledHtmlValidationFindingSchema).nullable().transform(value => value ?? undefined).optional(),
  html_validation_truncated: z.boolean().nullable().transform(value => value ?? undefined).optional(),
  document_language: z.union([z.string(), z.null()]).optional(),
  semantic_language: z.union([z.string(), z.null()]).optional(),
  hreflangs: z.array(CrawledHreflangSchema),
  amp_url: z.union([z.string(), z.null()]).optional(),
  amp_target_http_status: z.union([z.number().finite(), z.null()]).optional(),
  amp_target_checked_in_run: z.boolean().nullable().transform(value => value ?? undefined).optional(),
  amp_target_canonical_alignment: z.union([z.literal('canonical-to-source'), z.literal('self-canonical'), z.literal('canonical-points-elsewhere'), z.literal('missing-canonical'), z.null()]).optional(),
  h1_count: z.number().finite(),
  heading_counts: z.array(z.number().finite()).nullable().transform(value => value ?? undefined).optional(),
  duplicate_headings: z.array(CrawledDuplicateHeadingSchema).nullable().transform(value => value ?? undefined).optional(),
  pagination_next: z.union([z.string(), z.null()]).optional(),
  pagination_prev: z.union([z.string(), z.null()]).optional(),
  pagination_links: z.array(CrawledPaginationLinkSchema).nullable().transform(value => value ?? undefined).optional(),
  pagination_declaration_count: z.number().finite().nullable().transform(value => value ?? undefined).optional(),
  pagination_invalid_declaration_count: z.number().finite().nullable().transform(value => value ?? undefined).optional(),
  pagination_canonical_alignment: z.union([z.string(), z.null()]).optional(),
  internal_link_count: z.number().finite(),
  external_link_count: z.number().finite(),
  links: z.array(CrawledLinkSchema),
  images: z.array(CrawledImageSchema),
  frames: z.array(CrawledFrameSchema).nullable().transform(value => value ?? undefined).optional(),
  frames_truncated: z.boolean().nullable().transform(value => value ?? undefined).optional(),
  favicons: z.array(z.string()).nullable().transform(value => value ?? undefined).optional(),
  favicon_metadata: z.array(FaviconDataSchema).nullable().transform(value => value ?? undefined).optional(),
  favicon_resource_checks: z.array(CrawledSocialResourceCheckSchema).nullable().transform(value => value ?? undefined).optional(),
  social_meta_tags: z.array(CrawledSocialMetaTagSchema).nullable().transform(value => value ?? undefined).optional(),
  custom_search_results: z.array(CrawledCustomSearchResultSchema).nullable().transform(value => value ?? undefined).optional(),
  issues_count: z.number().finite(),
  issues: z.array(CrawledPageIssueSchema),
}).passthrough() satisfies z.ZodType<CrawledPageSummary, z.ZodTypeDef, unknown>;

export const CrawledResourceSchema = z.object({
  source_urls: z.array(z.string()),
  url: z.string(),
  resource_type: z.string(),
  http_status: z.number().finite().nullable().transform(value => value ?? undefined).optional(),
  content_type: z.string().nullable().transform(value => value ?? undefined).optional(),
  content_length: z.number().finite().nullable().transform(value => value ?? undefined).optional(),
  intrinsic_width: z.number().finite().nullable().transform(value => value ?? undefined).optional(),
  intrinsic_height: z.number().finite().nullable().transform(value => value ?? undefined).optional(),
  dimensions_source: z.string().nullable().transform(value => value ?? undefined).optional(),
  response_time_ms: z.number().finite().nullable().transform(value => value ?? undefined).optional(),
  request_error_kind: z.string().nullable().transform(value => value ?? undefined).optional(),
}).passthrough() satisfies z.ZodType<CrawledResource, z.ZodTypeDef, unknown>;
